cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blogHome, name='blogHome'),

    path('about', views.about, name='about'),

    path('archive', views.archive, name='archive'),

    path('entry/<int:blogEntry_id>/', views.entry, name='entry'),

    path('plan', views.plan, name='plan'),

    path('techtips+css', views.techTipsWithCss, name='techtips+css'),

    path('techtips-css', views.techTipsNoCss, name='techtips-css')

]

cs2610-FRANCOM-BRAXTON-assn2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

cs2610-FRANCOM-BRAXTON-assn2/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.index, name='index'),

	path('<int:question_id>/', views.detail, name='detail'),

	path('<int:question_id>/results/', views.results, name='results'),

	path('<int:question_id>/vote/', views.vote, name='vote'),
]

cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/models.py
import datetime
from django.db import models
from django.utils import timezone

class Blog(models.Model):
    title_text = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    content = models.TextField()
    posted = models.DateTimeField('date blog was published')

    def __str__(self):
        return self.title_text

    def was_published_recently(self):
        return self.posted >= timezone.now() - datetime.timedelta(days=1)



class Comments(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE,)
    commenter = models.CharField(max_length=200)
    email = models.EmailField()
    content = models.TextField()
    posted = models.DateTimeField('date comment was published')

    def __str__(self):
        return self.commenter

cs2610-FRANCOM-BRAXTON-assn2/mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from time import strftime

from .models import Blog, Comments

def blogHome(request):
    blogPost = Blog.objects.order_by('-posted')[:3]
    comments = Comments.objects.all()

    return render(request, 'blog/blogHome.html',
                  {"now": strftime("%c"),
                   "posts": blogPost,
                   "comments": comments
                   })

def entry(request, blogEntry_id):
    entry = get_object_or_404(Blog, pk=blogEntry_id)

    if request.POST:
        Comments(blog=entry, commenter=request.POST['commenter'], email=request.POST['email'],
                 content=request.POST['content'], posted=timezone.now()).save()
        return HttpResponseRedirect(reverse('blog:entry', args=(blogEntry_id,)))

    else:
        comments = Comments.objects.filter(blog=blogEntry_id).order_by('-posted')
        return render(request, 'blog/entry.html',
                      {"now": strftime("%c"),
                       "entry": entry,
                       "comments": comments,
                       })

def archive(request):
    blogPost = Blog.objects.order_by('-posted')

    return render(request, 'blog/archive.html',
                  {"now": strftime("%c"),
                   "posts": blogPost
                  })

def about(request):
    return render(request, 'blog/about.html',
                  {"now": strftime("%c")})

def plan(request):
    return render(request, 'blog/plan.html',
                  {"now": strftime("%c")})

def techTipsWithCss(request):
    return render(request, 'blog/techtips+css.html',
                  {"now": strftime("%c")})

def techTipsNoCss(request):
    return render(request, 'blog/techtips-css.html',
                  {"now": strftime("%c")})

cs2610-FRANCOM-BRAXTON-assn2/mysite/polls/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse
from django.template import loader

from django.shortcuts import get_object_or_404

from .models import Choice, Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {'latest_question_list': latest_question_list}
    return HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        print(request.POST)
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        print(question.choice_set)
        print(selected_choice)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        print(selected_choice)
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/templates/blog/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css"/>
        <title>About Me</title>
    </head>

    <body>
        <h1>All About Me (Shrek) &amp; More</h1>

        <ol>
            <li><a href="/blog">Blog</a></li>
            <li><a href="archive">Archive</a></li>
            <li><a href="about">About</a></li>
            <li><a href="techtips+css">Tech Tips - CSS edition</a></li>
            <li><a href="techtips-css">Tech Tips - No CSS</a></li>
            <li><a href="plan">Software Development Plan</a></li>
        </ol>

        <p>The current time is {{now}}</p>

        <p><img src="{% static 'blog/images/background.gif' %}" width="500" alt=""></p>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur id tempor ante. Duis magna
            lorem, scelerisque ut mi iaculis, semper pulvinar metus. Aenean eleifend arcu non dictum accum
            Integer efficitur rutrum eros, a varius elit ultrices non. Morbi non feugiat lorem. Aliquam
            fermentum volutpat interdum. Quisque ipsum dui, auctor sit amet nunc sed, feugiat consectetur mi.
            In fringilla metus vel nibh cursus, sit amet rhoncus dui dapibus. Curabitur odio eros, faucibus
            nec ligula id, pulvinar tincidunt erat. Fusce in malesuada dui. Donec risus odio, posuere in aliquam
            at, pellentesque ac turpis. Donec nec dolor at ante vehicula viverra. Sed gravida mollis arcu ut faucibus.
            Proin viverra sem nec ante pharetra, sit amet aliquet eros placerat. Orci varius natoque penatibus et
            magnis dis parturient montes, nascetur ridiculus mus.
        </p>

        <p><img src="{% static 'blog/images/ballshrek.jpg' %}" width="500" alt=""> <!-- This must be to an image linked in repository--></p>

        <p>
            Curabitur semper, diam tempus commodo malesuada, urna felis eleifend ipsum, nec elementum magna
            dolor sed est. Nam ornare egestas volutpat. Vestibulum eget viverra odio, ac fermentum purus. Etiam
            semper ac dui tincidunt rhoncus. Curabitur nisl urna, mollis ullamcorper vulputate sed, posuere id tortor.
            Vivamus sit amet porttitor massa. Quisque ipsum dui, auctor sit amet nunc sed, feugiat consectetur mi.
            In fringilla metus vel nibh cursus, sit amet rhoncus dui dapibus. Curabitur odio eros, faucibus
            nec ligula id, pulvinar tincidunt erat. Fusce in malesuada dui. Donec risus odio, posuere in aliquam
            at, pellentesque ac turpis. Vestibulum suscipit tortor sed mauris rhoncus, eu aliquet urna volutpat.
            Pellentesque vel sem faucibus, euismod odio eget, consequat nisi. Donec sit amet enim quis elit elementum
            porta. Curabitur sagittis efficitur ligula at euismod. Donec a volutpat arcu.
        </p>

        <p><img src="{% static 'blog/images/weddingshrek.jpg' %}" alt=""> <!-- This must be to an image linked in repository--></p>

        <p>
            Sed rhoncus facilisis lectus ac elementum. Nulla faucibus ultricies molestie. Curabitur ante lacus, feugiat
            in ex et, gravida pharetra sapien. Vivamus eget nulla vel tortor mattis pellentesque sed nec dolor. Aenean
            id tincidunt purus. Quisque ipsum dui, auctor sit amet nunc sed, feugiat consectetur mi.
            In fringilla metus vel nibh cursus, sit amet rhoncus dui dapibus. Curabitur odio eros, faucibus
            nec ligula id, pulvinar tincidunt erat. Fusce in malesuada dui. Donec risus odio, posuere in aliquam
            at, pellentesque ac turpis. Sed nec est nulla. Nullam cursus pellentesque est sed vestibulum. Etiam libero mauris,
            molestie non rutrum quis, elementum ut nunc. Nunc ornare egestas lectus, at consectetur leo varius sed.
        </p>

    </body>
</html>

cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/templates/blog/archive.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css"/>
    <title>Archive</title>
</head>
<body>

<h1>Archive</h1>

<ol>
    <li><a href="/blog">Blog</a></li>
    <li><a href="archive">Archive</a></li>
    <li><a href="about">About</a></li>
    <li><a href="techtips+css">Tech Tips - CSS edition</a></li>
    <li><a href="techtips-css">Tech Tips - No CSS</a></li>
    <li><a href="plan">Software Development Plan</a></li>
</ol>

<p>The current time is {{now}}</p>

<div>
    {% for post in posts %}
        <p><b><a href="{% url 'blog:entry' post.id %}">Blog post {{post.id}} about {{post | title}} ({{post.comments_set.all.count}} comment{{post.comments_set.all.count | pluralize}})</a></b></p>
        <p>{{post.author}}</p>
        <p>{{post.content | truncatewords:100 }}</p>
        <br>
    {% endfor %}

</div>

</body>
</html>

cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/templates/blog/blogHome.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css"/>
    <title>Shrek's Blog</title>
</head>
<body>

<div class="homeDisplay">
    <h1>Shrek's Blog</h1>
</div>

<ol>
    <li><a href="/blog">Blog</a></li>
    <li><a href="archive">Archive</a></li>
    <li><a href="about">About</a></li>
    <li><a href="techtips+css">Tech Tips - CSS edition</a></li>
    <li><a href="techtips-css">Tech Tips - No CSS</a></li>
    <li><a href="plan">Software Development Plan</a></li>
</ol>

<p>The current time is {{now}}</p>

<div>
    {% for post in posts %}
        <p><b><a href="{% url 'blog:entry' post.id %}">Blog post {{post.id}} about {{post | title}} ({{post.comments_set.all.count}} comment{{post.comments_set.all.count | pluralize}})</a></b></p>
        <p>{{post.author}}</p>
        <p>{{post.content | truncatewords:100 }}</p>
        <br>
    {% endfor %}
</div>

<div>
    <h2>Out of things to read??</h2>
    <p>There is more content for you in the <a href="{% url 'blog:archive' %}" >Archive</a></p>
</div>

</body>
</html>

cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/templates/blog/entry.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css"/>
    <title>Entry</title>
</head>
<body>

<h1>Blog post {{entry.id}} about {{entry.title_text | title }}</h1>
<h2>Author: {{entry.author}}</h2>

<ol>
    <li><a href="/blog">Blog</a></li>
    <li><a href="/blog/archive">Archive</a></li>
    <li><a href="/blog/about">About</a></li>
    <li><a href="/blog/techtips+css">Tech Tips - CSS edition</a></li>
    <li><a href="/blog/techtips-css">Tech Tips - No CSS</a></li>
    <li><a href="/blog/plan">Software Development Plan</a></li>
</ol>

<p>The current time is {{now}}</p>

<p>{{entry.content}}</p>
<br>
<h3>Thoughts? We'd love to hear from you!</h3>


<form action="{% url 'blog:entry'  entry.id %}" method="post">
{% csrf_token %}

<fieldset>
    <p>Your name: <input type="text" name="commenter" id="commenter"></p>
    <p>Your email address: <input type="email" name="email" id="email"></p>

    <textarea cols="50" rows="10" name="content" id="content" placeholder="Rant here..."></textarea>
</fieldset>
<input type="submit" value="Post Comment">
</form>


<h2>{{comments | length}} Comment{{comments | length | pluralize}}</h2>
{% for i in comments %}
    <p><b>{{i.commenter}} ({{i.email}})</b> said this at {{i.posted}}</p>
    <p>{{i.content}}</p>
{% endfor %}

</body>
</html>

cs2610-FRANCOM-BRAXTON-assn2/mysite/blog/templates/blog/plan.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" href="{% static 'blog/style.css' %}" type="text/css" />
        <title>Software Development Plan</title>
    </head>

    <body>

        <h1>Software Development Plan</h1>

        <ol>
            <li><a href="/blog">Blog</a></li>
            <li><a href="archive">Archive</a></li>
            <li><a href="about">About</a></li>
            <li><a href="techtips+css">Tech Tips - CSS edition</a></li>
            <li><a href="techtips-css">Tech Tips - No CSS</a></li>
            <li><a href="plan">Software Development Plan</a></li>
        </ol>

        <p>The current time is {{now}}</p>

        <div id="phase0">
            <h2>Phase 0: Requirements Specification</h2>

            <p>
                My goal is to build a fully functional, dynamic Django website. The website will have a homepage, an archive
                page that will show all of the blog posts, a entry page that will show a specific blog post and will have a
                form to add a comment to the page, and then I will have my about.html, techtips+css.html, and techtips-css.html
                pages as well.
            </p>
            <p>
                To be honest, I am pretty unfamiliar with everything. Django is very foreign to me and it is going to be
                a big learning curve. Obviously, I have already written the HTML and css for some of my webpage, but I
                have a lot of learning to do in order to be able to understand how to work those into the Django framework.
            </p>
        </div>

        <div id="phase1">
            <h2>Phase 1: System Analysis</h2>

            <p>
                Some of the data I will be using in this program will be taken from our last assignment. I am going to be using HTML files
                styled with CSS. I will have a form in one of the HTML files that will POST data to the server. I will want
                to put this data into our database as well as display it dynamically on our webpage.
            </p>
            <p>
                My output will be a fully functioning, dynamic Django website.
            </p>
            <p>
                There won't be any algorithms or formulae used in this program.
            </p>
        </div>

        <div id="phase2">
            <h2>Phase 2: Design</h2>
            <ul>
                <li>
                    The first step for me is to bring in my about.html, plan.html, techtips+css.html, and techtips-css.html
                    files and get them converted from static pages to dynamic django pages.
                </li>


                <li>
                    My next step is to make a blogHome.html, archive.html, and entry.html files. In addition to this, I
                    need to set up all of my models.py, urls.py, and views.py files. I will break down the functions and
                    classes that are going to be in these files in the following paragraphs.
                </li>


                <li>
                    models.py
                    <ul>
                        <li>
                            class Blog(models.Model)
                                <p>In this class I will need to make several class attributes that will make up a Blog object.
                                These attributes will be a title_text(models.CharField()), a author(models.CharField()), a
                                content(models.TextField()) and a posted(models.DateTimeField())</p>
                                <p>I will also need a method __str__(self) to return a string representation of the Blog object.</p>
                        </li>
                        <li>
                            class Comments(models.Model)
                                <p>In this class I will need to make several class attributes that will make up a Comments object.
                                These attributes will be a blog(models.ForeignKey()), a commenter(models.CharField()), a
                                email(models.EmailField()), a content(models.TextField()) and a posted(models.DateTimeField())</p>
                                <p>I will also need a method __str__(self) to return a string representation of the Comments object.</p>
                        </li>
                    </ul>
                </li>

                <li>
                    urls.py
                    <ul>
                        <li>
                            In urls.py I actually won't need to make any functions or classes. I will just need to add a
                            handful of paths() to the urlpatterns[] list so that all of my webpages are accessible.
                        </li>
                    </ul>
                </li>

                <li>
                    views.py
                    <ul>
                        <li>
                            def blogHome(request):
                                <p>In this function I will need to create a blogPost variable that will display the first 3
                                blog posts</p>
                                <p>I will also need to make a variable to access the comments</p>
                                <p>Then I will need to return an Http response with appropriate arguments. For my homepage
                                these will need to be a request, a url, and a dictionary that contains values to map to. I
                                can foresee me needing a time value, a posts value, and a comments value.</p>
                        </li>
                        <li>
                            def about(request):
                                <p>In this function I will just need to return an Http response with appropriate arguments.
                                    For my about page these will need to be a request, a url, and a dictionary that contains
                                    values to map to. I think all I will need for this one is a time value to make the page
                                    dynamic.
                                </p>
                        </li>
                        <li>
                            def archive(request):
                            <p>In this function I will need to create a blogPost variable that will display all of the
                                blog posts</p>
                                <p>Then I will need to return an Http response with appropriate arguments. For my archive page
                                these will need to be a request, a url, and a dictionary that contains values to map to. I
                                can foresee me needing a time value, and a posts value.</p>
                        </li>
                        <li>
                            def entry(request, blogEntry_id):
                                <p>In this function I will need to create a blogPost variable that will display the blog post
                                that was clicked on</p>
                                <p>I will also need to make a variable to access the comments</p>
                                <p>Then I will need to return an Http response with appropriate arguments. For my entry page
                                these will need to be a request, a url, and a dictionary that contains values to map to. I
                                can foresee me needing a time value, a posts value, and a comments value.</p>
                                <p>I will also need to somehow access the data from the POST that my entry.html form will
                                    make. I don't quite have a good approach for this yet, but I am sure that as I become
                                    more familiar with Django I will find a way to do this. The new comment will then be
                                    posted at the bottom of the page with the rest of them. </p>
                        </li>
                        <li>
                            def plan(request):
                                <p>In this function I will just need to return an Http response with appropriate arguments.
                                    For my plan page these will need to be a request, a url, and a dictionary that contains
                                    values to map to. I think all I will need for this one is a time value.
                                </p>
                        </li>
                        <li>
                            def techTipsWithCss(request):
                                <p>In this function I will just need to return an Http response with appropriate arguments.
                                    For my techTipsWithCss page these will need to be a request, a url, and a dictionary that contains
                                    values to map to. I think all I will need for this one is a time value to make the page
                                    dynamic.
                                </p>
                        </li>
                        <li>
                            def techTipsNoCss(request):
                                <p>In this function I will just need to return an Http response with appropriate arguments.
                                    For my techTipsNoCss page these will need to be a request, a url, and a dictionary that contains
                                    values to map to. I think all I will need for this one is a time value.
                                </p>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>

        <div id="phase3">
            <h2>Phase 3: Implementation</h2>

            <p>
                I implemented all of the above code to create a functional Django website.
            </p>
            <p>
                I learned that Django is a very powerful tool. I also learned that it has some pretty unique organization
                and syntax. It can be quite tricky at times figuring those things out but this project helped
                me to develop a lot more confidence in my ability to use Django.
            </p>
        </div>

        <div id="phase4">
            <h2>Phase 4: Testing and Debugging</h2>

            <h4>Test Case: I put 4 blogs into the system using http://127.0.0.1:8000/admin by hitting new Blog and then
            typing in the information it asks for.</h4>
            <p>My website only displayed the 3 most recent blog posts on my homepage and all 4 of them on my archive page.</p>

            <h4>Test Case: I added another comment to one of the blogs using http://127.0.0.1:8000/admin by hitting new
            comment button and arbitrarily typing in the information it asks for.</h4>
            <p>The number of comments on that particular blog post was updated on the bottom of the entry
            page, the homepage, and the archive page.</p>

            <h4>Test Case: I put 4 comments on one blog post into the system using http://127.0.0.1:8000/admin by hitting new
            comment button and arbitrarily typing in the information it asks for.</h4>
            <p>My website displayed all of the comments in order from newest to oldest order.</p>

        </div>

        <div id="phase5">
            <h2>Phase 5: Deployment</h2>

            <p>
                My project has been pushed to gitlab.
            </p>
        </div>

        <div id="phase6">
            <h2>Phase 6: Maintenance</h2>
            
            <p>
                My program is written quite well. I feel that my program became simpler as I coded because I started to
                more fully understand how Django works. Django is an awesome framework that makes the development of web
                apps pretty awesome once you understand how it all works together.
            </p>
            <p>
                I understand how all the parts of my program work. The complexity in this project is actually quite simple
                once you understand the flow in Django.
            </p>
            <p>
                If a bug was reported in a few months, I am very confident I would be able to find the cause very quickly.
            </p>
            <p>
                I believe that my documentation would make sense to myself in six months time and to anyone besides myself
                who understands Django due to the use of Django in this project.
            </p>
            <p>
                I would be able to add a new feature very easily to this project in a year because the layout of Django
                makes it easy to organize everything.
            </p>
            <p>
                My project should continue to work after upgrading my computers hardware, the operating system, and the
                next versions of Python or Django unless there was a major overhaul done on the syntax of Django.
            </p>
        </div>
        
    </body>

</html>    

cs2610-FRANCOM-BRAXTON-assn2/mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">

        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

cs2610-FRANCOM-BRAXTON-assn2/mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}	   </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

cs2610-FRANCOM-BRAXTON-assn2/mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>