fa22-cs2610-lecturenotes/cs2610proj/cs2610proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
]
urlpatterns += [path('polls/', include('polls.urls'))]
urlpatterns += [path('fib/', include('fib.urls'))]
urlpatterns += [path('hostname/', include('hostname.urls'))]
urlpatterns += [path('chars/', include('charactersheet.urls'))]

fa22-cs2610-lecturenotes/cs2610proj/fib/urls.py
from django.urls import path

from . import views


app_name = 'fib'
urlpatterns = [
    # /fib/fibAPI?N=[some non-negative number]
    path('fibAPI', views.fibAPI, name="fibAPI"),

    # /fib/
    path('', views.index, name="index"),
]

fa22-cs2610-lecturenotes/cs2610proj/fib/models.py
from django.db import models

# Create your models here.

fa22-cs2610-lecturenotes/cs2610proj/fib/views.py
from django.http import JsonResponse
from django.shortcuts import render


def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)


def fibAPI(request):
    # look at the GET paramters
    # if N is not present, return an error
    # if N is empty string or not an int, return an error
    # else, compute fibonacci of n (converted from string to int)
    # return JSON that contains N and the fib(N)
    for k, v in request.GET.items():
        print(f"  GET parameter {k} => {v}")
    resp = {}

    if 'N' not in request.GET:
        resp['error'] =  "Usage: N=[non-negative integer]"
    else:
        N = request.GET['N']
        if not N.isdigit():
            resp['error'] =  "Usage: N=[non-negative integer]"
        else:
            N = int(N)
            val = fibonacci(N)
            resp = {
                    'N': N,
                    'fibonacci': val
                    }

    j = JsonResponse(resp)
    # The HTTP status code does not count as an error as far as fetch() and the Promises are concerned
    # j.status_code = 501

    if 'Origin' in request.headers:
        j['Access-Control-Allow-Origin'] = request.headers['Origin']
    else:
        j['Access-Control-Allow-Origin'] = '*'

    return j


def index(request):
    return render(request, 'fib/index.html')

fa22-cs2610-lecturenotes/cs2610proj/fib/templates/fib/index.html
{% load static %}

<html>
	<head>
		<meta charset="utf-8">
		<title>Fibonacci numbers</title>
		<link href="{% static 'fib/style.css' %}" rel="stylesheet">
	</head>

	<body>
        <div>
            <div class="stuff-box blue shadowed">
				<h2>Compute the Nth Fibonacci number via our awesome API and <code>fetch()</code></h2>
                <input type="number" id="fib" name="fib">
                <button type="button" onclick="calculate()">Calculate</button>
				<h3 id="result"></h3>
				<p id="duration"></p>
            </div>
			<div id="fibonacci-slider" class="stuff-box red shadowed">
				<label for="list-slider" id="list-label">Fib(0)</label>
				<input id="list-slider" type="range" min="0" max="50" value="0" oninput="fiblist(this)">
			</div>
			<div> <a href="{% url 'fib:index' %}">Back</a> </div>
        </div>

		<script type="text/javascript" src="{% static 'fib/script.js' %}"></script>
	</body>
</html>